apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: be-app-core-vendorcoreservice
  name: be-app-core-vendorcoreservice
  namespace: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: be-app-core-vendorcoreservice
  template:
    metadata:
      labels:
        run: be-app-core-vendorcoreservice
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/eproc-holding-dev/app-core/vendorcoreservice:latest
        name: be-app-core-vendorcoreservice
        securityContext:
          capabilities:
            add: ["NET_RAW"]
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1024m
            ephemeral-storage: 2Gi
            memory: 4Gi
          requests:
            cpu: 100m
            ephemeral-storage: 128Mi
            memory: 256Mi
